version: "3.9"

services:
  shadow_postgres:
    image: postgres:15
    container_name: prisma_shadow_db
    restart: always
    ports:
      - "5433:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spycloud_shadow
    volumes:
      - shadow_data:/var/lib/postgresql/data

volumes:
  shadow_data:
